---
title: "2020-07-06 TidyTuesday - coffee"
author: "Sian Bladon"
date: "09/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(gghighlight)
```


# Read in data and clean


```{r read data, echo=TRUE, message=FALSE, warning=FALSE}
coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')

coffee_ratings <- coffee_ratings %>%
  mutate(country_of_origin = as.factor(country_of_origin))

coffee_ratings$country_of_origin <- recode_factor(coffee_ratings$country_of_origin, "Tanzania, United Republic Of" = "Tanzania", "United States (Hawaii)" = "US (Hawaii)")
```


# Identify top 10 producers and filter data


```{r filter by top 10, echo=TRUE, message=FALSE, warning=FALSE}
top_10 <- coffee_ratings %>%
  count(country_of_origin) %>%
  arrange(desc(n)) %>%
  top_n(10) %>%
  droplevels() %>%
  pull(country_of_origin)

top_producers <- coffee_ratings %>%
  filter(country_of_origin %in% top_10)
```


# Create plot


```{r create plot, fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
ggplot(top_producers, aes(x = total_cup_points, group = country_of_origin, colour = country_of_origin)) +
  geom_density(stat = "density", adjust = 2, size = 1) +
  xlim(55, 100) +
  gghighlight(unhighlighted_params = list(size = 1, colour = alpha("steelblue2", 0.3))) +
  facet_wrap(~ country_of_origin, nrow = 2) +
  scale_colour_viridis_d(option = "inferno", begin = 0.1, end = 0.9) +
  theme_minimal() +
  labs(title = "Total Cup Points of Coffee Bean Samples by Country of Origin",
       subtitle = "The total is calculated using scores for a variety of attributes, including aroma, acidity, \n body, flavour & sweetness. Data are the top 10 producers only.",
       x = "Total Cup Points",
       y = "Density") +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 16, face = "bold", family = "Helvetica", colour = "steelblue4", vjust = 4, hjust = 0.5),
    plot.subtitle = element_text(size = 14,  family = "Helvetica",colour = "steelblue4", vjust = 2, hjust = 0.5),
    axis.title.x = element_text(size = 14, face = "bold", family = "Helvetica", colour = "steelblue4", vjust = -2),
    axis.title.y = element_text(size = 14, face = "bold", family = "Helvetica", colour = "steelblue4", vjust = 2),
    axis.text.x = element_text(size = 12, family = "Helvetica", colour = "steelblue4"),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(size = 0.4),
    plot.background = element_rect(fill = "lightyellow"),
    panel.background = element_rect(fill = "lightyellow", colour = "lightyellow"),
    strip.text = element_text(size = 12, family = "Helvetica", colour = "steelblue4"),
    plot.margin = unit(c(1,1,1,1), "cm")
  )
```


